<head>
	<style type="text/css">
		#header{position: relative; height:100px; top:0px;}
		#header>div.empty
		{
			height:75px; width:100%;
			background: -webkit-linear-gradient(#1C1C1C,#383838,#404040,#383838,#1C1C1C);
			background: -o-linear-gradient(#1C1C1C,#383838,#404040,#383838,#1C1C1C); 
			background: -moz-linear-gradient(#1C1C1C,#383838,#404040,#383838,#1C1C1C); 
			background: linear-gradient(#1C1C1C,#383838,#404040,#383838,#1C1C1C);
		}
		.empty h1{color:#fff; font-size: 50px; font-family: "arial"; display: inline-block;}
		.empty img{margin-left: 10px; margin-top: 5px;}
		#navigation_panel{position: relative; background-color: #733C75; width: 100%; color:#fff; height:25px;}
		#navigation_panel ul{list-style-type: none; display: inline;}
		#navigation_panel ul li{display: inline; padding:4px 8px;}
		#navigation_panel ul li:hover{background-color: rgba(255,255,255,0.3);}
		#navigation_panel ul li:hover a{color:#000;}
		#navigation_panel ul li a{text-decoration: none; color:#fff; font-size: 20px;}
	</style>
</head>
<div id='header'>
	<div class='empty'>
		<img src="./imgs/header.png">
		<h1>FIND <span style='color:#733C75;'>MY</span> SIM</h1>
	</div>
	<div id='navigation_panel'>
			<ul>
				<li><a href="./index.php">Home</a></li>
				<li><a href="./aboutus.php">About Us</a></li>
				<li><a href="./contactus.php">Contact Us</a></li>
			</ul>
	</div>
</div>